export const GET_BLOG = "GET_BLOG"
export const GET_EVERY_BLOG = "GET_EVERY_BLOG"
export const POST_BLOG = "POST_BLOG"
export const UPDATE_BLOG = "UPDATE_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"